acq_loop:
  display_every_n: 1
  downsample: 12
  dropped_frame_warnings: false
  max_frames_to_acqure: null
cameras:
  face_cam:
    brand: uvc
    display:
      display_frames: true
      display_range: &id001 !!python/tuple
      - 0
      - 255
    exposure: 50
    gain: 50
    gamma: 340
    id: 0
    exposure_mode: 1
    exposure_priority: 0
    brightness: 32
    contrast: 100
    frame_size: &id002 !!python/tuple
      - 640
      - 400
    fps: 210
    name: face_cam
    roi:
    trigger:
      trigger_type: no_trigger
    writer:
      auto_remux_videos: true
      camera_name: face_cam
      codec: h264
      constqp: 18
      depth: false
      fmt: YUV420
      fps: 210
      gop: '30'
      gpu: 0
      idrperiod: '256'
      loglevel: error
      max_video_frames: 
      multipass: '0'
      output_px_format: yuv420p
      pixel_format: gray8
      preset: ultrafast
      profile: high
      quality: 15
      rc: constqp
      tuning_info: ultra_low_latency
      type: ffmpeg
      video_codec: libx264
globals:
  fps: 210
  microcontroller_required: false
rt_display:
  cameras_per_row: 1
  display_every_n: 6
  display_size: !!python/tuple
  - 640
  - 400
  downsample: 4
